In [2]:
import numpy as np

In [3]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = np.arange(9).reshape((3, 3))
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
rg=np.random.default_rng(1)
d=rg.random((1,5))
d

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145]])

In [15]:
e = np.arange(9)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
e= e.reshape((3, 3))
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.concatenate((a1, a2))
a3

array([1, 2, 3, 4, 5, 6])

In [20]:
f=np.arange(15).reshape(3,5)
g=np.arange(15,30).reshape(3,5)

In [22]:
h=f+g
h

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [23]:
i=f-g
i

array([[-15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -15]])

In [24]:
j=f*g
j

array([[  0,  16,  34,  54,  76],
       [100, 126, 154, 184, 216],
       [250, 286, 324, 364, 406]])

In [26]:
k=f/g
k

array([[0.        , 0.0625    , 0.11764706, 0.16666667, 0.21052632],
       [0.25      , 0.28571429, 0.31818182, 0.34782609, 0.375     ],
       [0.4       , 0.42307692, 0.44444444, 0.46428571, 0.48275862]])

In [31]:
a1=np.arange(15).reshape(3,5)
a2=np.arange(15,30).reshape(5,3)

In [32]:
a3=a1@a2
a3

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [38]:
a=  np.random.rand(3, 3, 3)
a

array([[[0.32201825, 0.59859208, 0.60314109],
        [0.79394064, 0.31839195, 0.55119242],
        [0.03291416, 0.58320091, 0.90710914]],

       [[0.07947947, 0.19006853, 0.07721614],
        [0.83253434, 0.5946728 , 0.53827756],
        [0.327886  , 0.40244777, 0.52813293]],

       [[0.87111934, 0.76587502, 0.53903459],
        [0.84298111, 0.32409288, 0.21846754],
        [0.92282486, 0.63264085, 0.22577248]]])

In [40]:
a.sum()

13.624024824444374

In [41]:
a.mean()

0.5045935120164583

In [42]:
a.std()

0.2643115703312241