<a href="https://colab.research.google.com/github/PranitaAbbireddy/pre-bootcamp/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=[[1,2,3],[1,2,3],[1,2,3]]

In [2]:
a

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [3]:
a[0][1]

2

In [4]:
b=a

In [5]:
b

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [6]:
import numpy as np

In [8]:
arr=np.array([2,3,4])
arr

array([2, 3, 4])

In [11]:
arr2=np.array([(2,3),(3,4)])
arr2

array([[2, 3],
       [3, 4]])

In [12]:
type(arr2)

numpy.ndarray

In [14]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3,4,5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [16]:
np.empty((2,3))

array([[2.95328807e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [18]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [19]:
np.arange(10,30,5).reshape(2,2)

array([[10, 15],
       [20, 25]])

In [22]:
rg=np.random.default_rng(1)

In [23]:
a=rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [24]:
a.ndim

2

In [25]:
a.shape

(2, 3)

In [26]:
a.size

6

In [27]:
a.dtype

dtype('float64')

In [28]:
a=np.array([2,3,4],dtype=int)
a

array([2, 3, 4])

In [29]:
a=np.array([2,3.2,4],dtype=object)
a

array([2, 3.2, 4], dtype=object)

In [30]:
a.dtype

dtype('O')

In [32]:
type(a[0])

int

In [31]:
a.data

In [38]:
a=np.arange(15).reshape(3,5)
b=np.arange(15,30).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
b

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [40]:
c=a+b
c

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [41]:
d=b-a
d

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [42]:
e=a*b
e

array([[  0,  16,  34,  54,  76],
       [100, 126, 154, 184, 216],
       [250, 286, 324, 364, 406]])

In [43]:
f=np.arange(15).reshape(3,5)
g=np.arange(15,30).reshape(5,3)

In [44]:
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
g

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [46]:
h=f@g
h

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [47]:
f.dot(g)

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [48]:
a+=2
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [49]:
a**2

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256]])

In [50]:
np.sin(a)

array([[ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332]])

In [51]:
a.max()

16

In [52]:
a.sum()

135

In [53]:
a.min()

2

In [54]:
a.mean()

9.0

In [55]:
a.sum(axis=0)

array([21, 24, 27, 30, 33])

In [56]:
a.sum(axis=1)

array([20, 45, 70])

In [57]:
np.exp(a)

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
        4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03, 2.20264658e+04,
        5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
        8.88611052e+06]])

In [60]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ]])

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [58]:
np.add(a,b)

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45]])

In [61]:
a[0][0]

2

In [62]:
a.T

array([[ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15],
       [ 6, 11, 16]])

In [63]:
a.shape

(3, 5)

In [66]:
a.resize(5,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [67]:
a.shape

(5, 3)

In [68]:
c=a.reshape(3,5)
c

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [69]:
c.shape

(3, 5)

In [71]:
a = np.arange(15).reshape(3,5)
b = np.arange(15,30).reshape(3,5)

In [72]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
b

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [81]:
c= np.hstack((a,b))
c

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [75]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [82]:
np.hsplit(c,10)

[array([[ 0],
        [ 5],
        [10]]), array([[ 1],
        [ 6],
        [11]]), array([[ 2],
        [ 7],
        [12]]), array([[ 3],
        [ 8],
        [13]]), array([[ 4],
        [ 9],
        [14]]), array([[15],
        [20],
        [25]]), array([[16],
        [21],
        [26]]), array([[17],
        [22],
        [27]]), array([[18],
        [23],
        [28]]), array([[19],
        [24],
        [29]])]

In [84]:
np.hsplit(c,(3,7))

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12]]), array([[ 3,  4, 15, 16],
        [ 8,  9, 20, 21],
        [13, 14, 25, 26]]), array([[17, 18, 19],
        [22, 23, 24],
        [27, 28, 29]])]

In [85]:
c=a.view()
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
b=a

In [89]:
a.data

In [90]:
b.data

In [87]:
b is a

True

In [88]:
c is a

False