<a href="https://colab.research.google.com/github/lokesh116/pre-bootcamp/blob/main/test3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
c = np.arange(9).reshape((3, 3))
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
rg=np.random.default_rng(1)
d=rg.random((1,5))
d

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145]])

In [6]:
e = np.arange(9)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
e= e.reshape((3, 3))
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.concatenate((a1, a2))
a3

array([1, 2, 3, 4, 5, 6])

In [9]:
f=np.arange(15).reshape(3,5)
g=np.arange(15,30).reshape(3,5)

In [10]:
h=f+g
h

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [11]:
i=f-g
i

array([[-15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -15]])

In [12]:
j=f*g
j

array([[  0,  16,  34,  54,  76],
       [100, 126, 154, 184, 216],
       [250, 286, 324, 364, 406]])

In [13]:
k=f/g
k

array([[0.        , 0.0625    , 0.11764706, 0.16666667, 0.21052632],
       [0.25      , 0.28571429, 0.31818182, 0.34782609, 0.375     ],
       [0.4       , 0.42307692, 0.44444444, 0.46428571, 0.48275862]])

In [14]:
a1=np.arange(15).reshape(3,5)
a2=np.arange(15,30).reshape(5,3)

In [15]:
a3=a1@a2
a3

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [16]:
a=  np.random.rand(3, 3, 3)
a

array([[[0.04287739, 0.21745297, 0.1169975 ],
        [0.36558037, 0.27771907, 0.38349692],
        [0.67982549, 0.45337379, 0.0800746 ]],

       [[0.89624754, 0.89426944, 0.28945559],
        [0.69858049, 0.75187217, 0.10780238],
        [0.43204993, 0.56710308, 0.11265649]],

       [[0.04645402, 0.48845667, 0.62145917],
        [0.17631082, 0.91455213, 0.32585881],
        [0.38665954, 0.96924673, 0.13409779]]])

In [17]:
a.sum()

11.430530893504283

In [18]:
a.mean()

0.4233529960557142

In [19]:
a.std()

0.2877671551005011