In [1]:
import numpy as np

 Create a 2-dimensional array of size 2x3 with all elements set to 0

In [3]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

Create a 1-dimensional array of size 10 with values ranging from 0 to 9

In [6]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2-dimensional array of size 3x3 with values ranging from 0 to 8

In [8]:
c=np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 1-dimensional array of size 5 with random integer values

In [19]:
d=np.random.randint(0,500,size=5)
d

array([ 58, 113, 223,  41, 441])

Reshape a 1-dimensional array of size 9 into a 3x3 2-dimensional array

In [24]:
e=np.ones(9).reshape(3,3)
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

 Create and concatenate two 1-dimensional arrays of size 3 into a single array of size 6

In [25]:
f=np.array([4,5,6])
g=np.array([7,8,9])

In [27]:
h=np.hstack((f,g))
h

array([4, 5, 6, 7, 8, 9])

Perform element-wise addition, subtraction, multiplication, and division of two 2-dimensional arrays of size 3x3

In [39]:
i=np.arange(0,9).reshape(3,3)
j=np.arange(10,19).reshape(3,3)
i


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
j

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [36]:
k=i+j
k


array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [37]:
l=i-j
l



array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [38]:
m=i@j
m


array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

In [41]:
n=i/j
n

array([[0.        , 0.09090909, 0.16666667],
       [0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444]])

Create and compute the dot product of two arrays

In [42]:
o=np.arange(21,29)
o

array([21, 22, 23, 24, 25, 26, 27, 28])

In [43]:
p=np.arange(30,38)
p

array([30, 31, 32, 33, 34, 35, 36, 37])

In [44]:
p.dot(o)

6608

Create and compute the sum, mean, and standard deviation of a 3-dimensional array of size 3x3x3.


In [55]:
q=np.arange(0,27).reshape(3,3,3)
q


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [56]:
sum=np.sum(q)
sum

351

In [57]:
mean=np.mean(q)
mean

13.0

In [58]:
std=np.std(q)
std

7.788880963698615