In [1]:
a = [[1,2,3],[1,2,3],[1,2,3]]

In [2]:
a

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [3]:
a[0][1]

2

In [4]:
b =  a

In [5]:
b

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [8]:
!pip install numpy

In [9]:
!conda install numpy

^C


In [10]:
import numpy as np

# Array Creation

In [11]:
arr = np.array([2,3,4])

In [12]:
arr

array([2, 3, 4])

In [14]:
arr2 = np.array([(2,3),(3,4)])

In [15]:
arr2

array([[2, 3],
       [3, 4]])

In [16]:
type(arr2)

numpy.ndarray

In [17]:
a = np.zeros((3,4))

In [18]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2,3,4,5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [20]:
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.06811354e-306, 1.89146896e-307, 7.56571288e-307]])

In [26]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [27]:
np.arange(10,30,5).reshape(2,2)

array([[10, 15],
       [20, 25]])

In [28]:
rg = np.random.default_rng(1)

In [33]:
a = rg.random((2,3,4))

In [37]:
a

array([[[0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 ],
        [0.30319483, 0.45349789, 0.1340417 , 0.40311299]],

       [[0.20345524, 0.26231334, 0.75036467, 0.28040876],
        [0.48519097, 0.9807372 , 0.96165719, 0.72478994],
        [0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

# Common Functions

In [34]:
a.ndim

3

In [35]:
a.shape

(2, 3, 4)

In [36]:
a.size

24

In [38]:
a.dtype

dtype('float64')

In [48]:
a = np.array([2,3.2,4],dtype=object)

In [49]:
a

array([2, 3.2, 4], dtype=object)

In [52]:
type(a[0])

int

In [51]:
a.data

# Basic Operation

In [53]:
a = np.arange(15).reshape(3,5)

In [60]:
b = np.arange(15,30).reshape(3,5)

In [61]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
b

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [63]:
c = a + b

In [64]:
c

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [65]:
d = b - a
d

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [66]:
e = a * b

In [67]:
e

array([[  0,  16,  34,  54,  76],
       [100, 126, 154, 184, 216],
       [250, 286, 324, 364, 406]])

In [69]:
f = np.arange(15).reshape(3,5)

In [70]:
g = np.arange(15,30).reshape(5,3)

In [71]:
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
g

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [73]:
h = f @ g

In [74]:
h

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [75]:
f.dot(g)

array([[ 240,  250,  260],
       [ 765,  800,  835],
       [1290, 1350, 1410]])

In [76]:
a += 2

In [77]:
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [78]:
a**2

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256]], dtype=int32)

In [79]:
np.sin(a)

array([[ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332]])

In [81]:
a.max()

16

In [82]:
a.sum()

135

In [83]:
a.min()

2

In [84]:
a.mean()

9.0

In [85]:
a.sum(axis = 0)

array([21, 24, 27, 30, 33])

In [86]:
a.sum(axis = 1)

array([20, 45, 70])

In [87]:
np.exp(a)

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
        4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03, 2.20264658e+04,
        5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
        8.88611052e+06]])

In [88]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [89]:
np.add(a,b)

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45]])

In [92]:
a[0][0]

2

In [93]:
a.T

array([[ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15],
       [ 6, 11, 16]])

# Chanigng the size of array

In [95]:
# reshape
# resize

In [97]:
a.shape

(3, 5)

In [103]:
a.resize(5,3)

In [105]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [106]:
a.shape

(5, 3)

In [107]:
c = a.reshape(3,5)

In [108]:
c

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [109]:
c.shape

(3, 5)

# Stacking array

In [111]:
a = np.arange(15).reshape(3,5)

In [112]:
b = np.arange(15,30).reshape(3,5)

In [113]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
b

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [117]:
c =np.hstack((a,b)) 

In [118]:
d = np.vstack((a,b))

# Splitting the arrays

In [121]:
c

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [124]:
c.size

30

In [125]:
np.hsplit(c,10)

[array([[ 0],
        [ 5],
        [10]]),
 array([[ 1],
        [ 6],
        [11]]),
 array([[ 2],
        [ 7],
        [12]]),
 array([[ 3],
        [ 8],
        [13]]),
 array([[ 4],
        [ 9],
        [14]]),
 array([[15],
        [20],
        [25]]),
 array([[16],
        [21],
        [26]]),
 array([[17],
        [22],
        [27]]),
 array([[18],
        [23],
        [28]]),
 array([[19],
        [24],
        [29]])]

In [127]:
np.hsplit(c,(3,7))

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12]]),
 array([[ 3,  4, 15, 16],
        [ 8,  9, 20, 21],
        [13, 14, 25, 26]]),
 array([[17, 18, 19],
        [22, 23, 24],
        [27, 28, 29]])]

# Copying numpy arrays

In [128]:
b = a

In [129]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
a.data

In [132]:
b.data

In [135]:
c = a.view()

In [136]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
c.data

In [138]:
b is a

True

In [139]:
c is a

False